### ISSUE TITLE
Module" win32crypt" not found in Win 11 

### ISSUE THREAD

**Issue by VuDn5** [VirtualCable/uds-client#2]
Dear @dkmstr   
Error like below:  
![image](https://github.com/VirtualCable/uds-client/assets/36143595/69f84475-f6ba-4b2f-9726-4eee157d64c7)
when i run in Windows 11.

**Comment by dkmstr** [comment]
How have you created the executable?
If your are using pyinstaller, you will need to added 
"hiddenimports=['win32crypt', 'certifi']"
To your spec in order to run...
I prefer not to add it to os_detector because the error is due to not being included in the builder, not in the source...
I have it compiled and works perfectly... ;-)
